/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_example_liushanpu_myndkdemo_Hello.h>
/* Header for class com_example_liushanpu_myndkdemo_Hello */

/*
 * Class:     com_example_liushanpu_myndkdemo_Hello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_liushanpu_myndkdemo_Hello_sayHello
  (JNIEnv *env, jclass jclass) {
    return env->NewStringUTF("hello from cpp");
  }
